name: Build ModoPurga

on:
  push:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Compilar con Maven
        run: mvn -B clean package

      - name: Guardar el .jar como Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ModoPurga
          path: target/ModoPurga.jar
